//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Salary
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public double BaseSalary { get; set; }
        public Nullable<double> Bouns { get; set; }
        public Nullable<double> Minus { get; set; }
        public double TotalSalary { get; set; }
        public int Employee_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
