//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Purchase_Order_Detalis = new HashSet<Purchase_Order_Detalis>();
            this.Purchase_Returned_Cheque_Details = new HashSet<Purchase_Returned_Cheque_Details>();
            this.Sales_Order_Details = new HashSet<Sales_Order_Details>();
            this.Sales_Returned_Cheque_Details = new HashSet<Sales_Returned_Cheque_Details>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public string Discription { get; set; }
        public double SalePrice { get; set; }
        public int Quantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Order_Detalis> Purchase_Order_Detalis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Returned_Cheque_Details> Purchase_Returned_Cheque_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Order_Details> Sales_Order_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Returned_Cheque_Details> Sales_Returned_Cheque_Details { get; set; }
    }
}
