//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase_Order()
        {
            this.Purchase_Order_Detalis = new HashSet<Purchase_Order_Detalis>();
            this.Purchase_Returned_Cheque = new HashSet<Purchase_Returned_Cheque>();
        }
    
        public int Id { get; set; }
        public int InvoiceNo { get; set; }
        public System.DateTime RecivedDate { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public string Type { get; set; }
        public int NumOfProducts { get; set; }
        public int InvoiceAmount { get; set; }
        public int Paid_Amount { get; set; }
        public int Remain_Amount { get; set; }
        public int Order_Id { get; set; }
        public int Supplier_Id { get; set; }
    
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Order_Detalis> Purchase_Order_Detalis { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Returned_Cheque> Purchase_Returned_Cheque { get; set; }
    }
}
