//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Returned_Cheque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales_Returned_Cheque()
        {
            this.Sales_Returned_Cheque_Details = new HashSet<Sales_Returned_Cheque_Details>();
        }
    
        public int Id { get; set; }
        public int NumOfProducts { get; set; }
        public System.DateTime Date { get; set; }
        public int Sales_Order_Id { get; set; }
    
        public virtual Sales_Order Sales_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Returned_Cheque_Details> Sales_Returned_Cheque_Details { get; set; }
    }
}
