//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales_Order()
        {
            this.Sales_Order_Details = new HashSet<Sales_Order_Details>();
            this.Sales_Returned_Cheque = new HashSet<Sales_Returned_Cheque>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public int NumOfProducts { get; set; }
        public double InvoiceAmount { get; set; }
        public Nullable<double> InvoiceDiscount { get; set; }
        public double TotalAmount { get; set; }
        public int Order_Id { get; set; }
        public int Customer_Id { get; set; }
        public Nullable<int> PaidAmount { get; set; }
        public Nullable<int> RemainAmount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Order_Details> Sales_Order_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Returned_Cheque> Sales_Returned_Cheque { get; set; }
    }
}
